### ISSUE TITLE
Enable 2FA for all Mojaloop GitHub users

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/design-authority-project#102]
## Request Summary: 

I'd like to discuss "enabling two-factor authentication for all Mojaloop GitHub users"

## **Request Details**:

- **Deadline:** Not urgent, but would like to discuss during the 16th April 2023 meeting
- **Impact (Teams):** Improves security, 2FA is a widely accepted security mechanism. But this would also disable access to any users in teams part of Mojaloop (Read access will not be affected to public Mojaloop repositories)
- **Impact (Components):** No impact to components

<insert more information about your request>

**Artifacts**:
- [ ] None

**Dependencies**:
- [ ] No dependencies

### **Accountability**:
- **Owner:** Sam Kummary (@elnyry-sam-k )
- **Raised By:** Sam Kummary (@elnyry-sam-k )

## **Decision(s)**:

<fill in this section upon reaching a decision>

- **Approved By:** <Insert name>
  
### Details

- [ ] Actual decision made as a result of discussion

## **Follow-up**:

<fill in this section upon reaching a decision>
  
- [ ] Actions to implement the decisions

**Comment by mdebarros** [comment]
MFA token to authenticate access to my AWS resources through the AWS CLI (ref: https://repost.aws/knowledge-center/authenticate-mfa-cli) has the following expiration restrictions: 
- Minimum: 15 minutes for normal Users & Root
- Maximum: 36 hours for Users & 1 hour for Root

**Comment by mdebarros** [comment]
## Findings

There are two main issues for enabling MFA Authentication for Automated CI Accounts:

MFA token to authenticate access to my AWS resources through the AWS CLI (ref: [https://repost.aws/knowledge-center/authenticate-mfa-cli)](https://repost.aws/knowledge-center/authenticate-mfa-cli) "‌") has the following expiration restrictions:
Minimum: 15 minutes for normal Users & Root
Maximum: 36 hours for Users & 1 hour for Root
‌
MFA Devices for shared Accounts (i.e. Automated CI Accounts) require paid services such as 1Password or BitWarden. There are some non-paid options, but those tend to be a security risk.
‌
## Recommendation for CI/Automated accounts:

1. MFA is impractical
2. Should NOT have console/UI access
3. Rather ensure minimum access/policies for each of those accounts, and consider creating different accounts that are more focused with limited access to AWS instead of “general” all-access account.

**Comment by elnyry-sam-k** [comment]
Miguel's above comment was related to AWS accounts, GitHub accounts are fine and are addressed. This can be closed.

Implemented on August 16th, 2023.
