### ISSUE TITLE
Investigate solution to avoid recompiling node-rkafka at each npm install both in docker and in host

### ISSUE THREAD

**Issue by claudio-viola** [mojaloop/design-authority-project#57]
## **Request**:
- Discuss https://github.com/mojaloop/project/issues/1461 . Node-rkafka compilation  / recompilation takes away a lot of developer time from compiling docker container**s** and service**s** locally everytime a change in package.json happens (so far very frequently)
**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner:

**Comment by claudio-viola** [comment]
This 'hack' could be used to at least have the cache of docker file when we just bump package version  and /or update test commands... There is another possible approach which would mean 'splitting' package files.
https://stackoverflow.com/questions/51110793/bumping-package-json-version-without-invalidating-docker-cache

**Comment by godfreykutumela** [comment]
Hi, @claudio-viola @lewisdaly @elnyry-sam-k, can you please advise regarding the status of this issue?

**Comment by MichaelJBRichards** [comment]
PSB: Solution is to install dependencies locally MdB: only helps with local deploys, does not help with Docker; MdB does not have this issue.

**Comment by mdebarros** [comment]
@pedrosousabarreto and I agree that this can be resolved as per the following Dockerfile implementation in the vNext: https://github.com/mojaloop/transfers-bc/blob/main/packages/command-handler-svc/Dockerfile

The only change to the above Dockerfile being that we should install the [librdkafka](https://pkgs.alpinelinux.org/package/edge/community/x86/librdkafka) dependency instead of the development lib version [librdkafka-dev](https://pkgs.alpinelinux.org/package/edge/community/x86/librdkafka-dev).
