### ISSUE TITLE
Mojaloop Issue Logging Mechanism and process

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority-project#63]
## **Request**:
As we’re getting more and more community contributors, I notice that newcomers don’t always use the unified mojaloop/project issue tracker. I know we’ve talked in the past about the pros and cons of having central issue trackers, but I’d love to discuss this as a DA.
Options:
1. Disable github issues on all repos, and update readme docs to ask people to use the central issue tracker in mojaloop/project
2. Add issue templates in all repos (to improve the quality of issues), and find a better way to keep track of issues in individual projects

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner:

**Comment by NicoDuvenage** [comment]
As discussed in the DA meeting, the current approach of loading an issue in the repository where the issue is applicable and not on the project board itself.
It is then the responsibility of the Product Owners and Scrum Master to gather those issues (all obviously applicable to the Core OSS Development) and create issues specific to the Project Board with links and references to the original.
There was no opposition to continuing with this approach.

**Comment by lewisdaly** [comment]
Thanks everyone. I agree that keeping issues as close to their repos makes sense, and perhaps we can improve the systems around these issues to make sure that we don't lose important community contributions because they aren't on the main `/project` repo.

A few suggestions:
1. Add a github issue template to every repository
  > This won't be too hard, since we have some existing mass PR tools
2. Set up some sort of weekly new issue digest so that new issues opened on repos don't go missing
3. Go through and close existing issues on individual repos that are out of date
4. Add more repos to our zenhub account, so we can easily add them to the master scrum board 
e.g.
<img width="326" alt="Screen Shot 2020-08-12 at 8 41 46 pm" src="https://user-images.githubusercontent.com/1683980/90016250-48c4e300-dcdc-11ea-99ec-19f2be14426f.png">
